package com.pixelvibe.vedioplayer.ui.theme

import androidx.compose.ui.graphics.Color

// ─────────────────────────────────────────────
// Theme definitions with light/dark/AMOLED variants
// ─────────────────────────────────────────────

data class AppThemeColors(
    val primary: Color,
    val onPrimary: Color,
    val primaryContainer: Color,
    val onPrimaryContainer: Color,
    val secondary: Color,
    val onSecondary: Color,
    val secondaryContainer: Color,
    val onSecondaryContainer: Color,
    val tertiary: Color,
    val onTertiary: Color,
    val tertiaryContainer: Color,
    val onTertiaryContainer: Color,
    val error: Color,
    val onError: Color,
    val errorContainer: Color,
    val onErrorContainer: Color,
    val background: Color,
    val onBackground: Color,
    val surface: Color,
    val onSurface: Color,
    val surfaceVariant: Color,
    val onSurfaceVariant: Color,
    val outline: Color,
    val outlineVariant: Color,
    val scrim: Color,
    val inverseSurface: Color,
    val inverseOnSurface: Color,
    val inversePrimary: Color,
    val surfaceTint: Color,
    // AMOLED
    val amoledBackground: Color = Color.Black,
    val amoledSurface: Color = Color.Black,
)

// ── Default ──
val DefaultLight = AppThemeColors(
    primary = Color(0xFF6750A4),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFEADDFF),
    onPrimaryContainer = Color(0xFF21005D),
    secondary = Color(0xFF625B71),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFE8DEF8),
    onSecondaryContainer = Color(0xFF1D192B),
    tertiary = Color(0xFF7D5260),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFD8E4),
    onTertiaryContainer = Color(0xFF31111D),
    error = Color(0xFFB3261E),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFF9DEDC),
    onErrorContainer = Color(0xFF410E0B),
    background = Color(0xFFFFFBFE),
    onBackground = Color(0xFF1C1B1F),
    surface = Color(0xFFFFFBFE),
    onSurface = Color(0xFF1C1B1F),
    surfaceVariant = Color(0xFFE7E0EC),
    onSurfaceVariant = Color(0xFF49454F),
    outline = Color(0xFF79747E),
    outlineVariant = Color(0xFFC4C7C5),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFF313033),
    inverseOnSurface = Color(0xFFF4EFF4),
    inversePrimary = Color(0xFFD0BCFF),
    surfaceTint = Color(0xFF6750A4),
)

val DefaultDark = AppThemeColors(
    primary = Color(0xFFD0BCFF),
    onPrimary = Color(0xFF381E72),
    primaryContainer = Color(0xFF4F378B),
    onPrimaryContainer = Color(0xFFEADDFF),
    secondary = Color(0xFFCCC2DC),
    onSecondary = Color(0xFF332D41),
    secondaryContainer = Color(0xFF4A4458),
    onSecondaryContainer = Color(0xFFE8DEF8),
    tertiary = Color(0xFFEFB8C8),
    onTertiary = Color(0xFF492532),
    tertiaryContainer = Color(0xFF633B48),
    onTertiaryContainer = Color(0xFFFFD8E4),
    error = Color(0xFFF2B8B5),
    onError = Color(0xFF601410),
    errorContainer = Color(0xFF8C1D18),
    onErrorContainer = Color(0xFFF9DEDC),
    background = Color(0xFF1C1B1F),
    onBackground = Color(0xFFE6E1E5),
    surface = Color(0xFF1C1B1F),
    onSurface = Color(0xFFE6E1E5),
    surfaceVariant = Color(0xFF49454F),
    onSurfaceVariant = Color(0xFFCAC4D0),
    outline = Color(0xFF938F99),
    outlineVariant = Color(0xFF49454F),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFFE6E1E5),
    inverseOnSurface = Color(0xFF313033),
    inversePrimary = Color(0xFF6750A4),
    surfaceTint = Color(0xFFD0BCFF),
)

// ── Catppuccin ──
val CatppuccinLight = AppThemeColors(
    primary = Color(0xFFDC8A78),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFDAD3),
    onPrimaryContainer = Color(0xFF4E241E),
    secondary = Color(0xFFEA76CB),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFFFD5EE),
    onSecondaryContainer = Color(0xFF4D1444),
    tertiary = Color(0xFFDF8E1D),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFDEAA),
    onTertiaryContainer = Color(0xFF3A2400),
    error = Color(0xFFD20F39),
    onError = Color(0xFFFFFFFF),
    background = Color(0xFFEFF1F5),
    onBackground = Color(0xFF4C4F69),
    surface = Color(0xFFEFF1F5),
    onSurface = Color(0xFF4C4F69),
    surfaceVariant = Color(0xFFCCD0DA),
    onSurfaceVariant = Color(0xFF5C5F77),
    outline = Color(0xFF8C8FA1),
    outlineVariant = Color(0xFFBCC0CC),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFF4C4F69),
    inverseOnSurface = Color(0xFFEFF1F5),
    inversePrimary = Color(0xFFFFB5A7),
    surfaceTint = Color(0xFFDC8A78),
)

val CatppuccinDark = AppThemeColors(
    primary = Color(0xFFDC8A78),
    onPrimary = Color(0xFF241512),
    primaryContainer = Color(0xFF3A2420),
    onPrimaryContainer = Color(0xFFFFDAD3),
    secondary = Color(0xFFF5BDEE),
    onSecondary = Color(0xFF38203E),
    secondaryContainer = Color(0xFF4A2B48),
    onSecondaryContainer = Color(0xFFFFD5EE),
    tertiary = Color(0xFFF5A97F),
    onTertiary = Color(0xFF2E1C00),
    tertiaryContainer = Color(0xFF432B00),
    onTertiaryContainer = Color(0xFFFFDEAA),
    error = Color(0xFFF38BA8),
    onError = Color(0xFF3D0712),
    errorContainer = Color(0xFF5C0B1A),
    onErrorContainer = Color(0xFFFFD9E0),
    background = Color(0xFF303446),
    onBackground = Color(0xFFCDD6F4),
    surface = Color(0xFF303446),
    onSurface = Color(0xFFCDD6F4),
    surfaceVariant = Color(0xFF45475A),
    onSurfaceVariant = Color(0xFFBCC0CC),
    outline = Color(0xFF9399B2),
    outlineVariant = Color(0xFF585B70),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFFCDD6F4),
    inverseOnSurface = Color(0xFF303446),
    inversePrimary = Color(0xFFBA6B5A),
    surfaceTint = Color(0xFFDC8A78),
)

// ── Gruvbox ──
val GruvboxLight = AppThemeColors(
    primary = Color(0xFFAF3A03),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFDBCF),
    onPrimaryContainer = Color(0xFF3D0E00),
    secondary = Color(0xFF6B5C42),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFF5E0C0),
    onSecondaryContainer = Color(0xFF251A06),
    tertiary = Color(0xFF536433),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFD6E9AB),
    onTertiaryContainer = Color(0xFF141F00),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    background = Color(0xFFFFFBFF),
    onBackground = Color(0xFF201A18),
    surface = Color(0xFFFFFBFF),
    onSurface = Color(0xFF201A18),
    surfaceVariant = Color(0xFFF5DED4),
    onSurfaceVariant = Color(0xFF53433D),
    outline = Color(0xFF85736C),
    outlineVariant = Color(0xFFD8C2BA),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFF362F2C),
    inverseOnSurface = Color(0xFFFBEEEB),
    inversePrimary = Color(0xFFFFB59B),
    surfaceTint = Color(0xFFAF3A03),
)

val GruvboxDark = AppThemeColors(
    primary = Color(0xFFFFB59B),
    onPrimary = Color(0xFF5C1A00),
    primaryContainer = Color(0xFF862B00),
    onPrimaryContainer = Color(0xFFFFDBCF),
    secondary = Color(0xFFD7C3A4),
    onSecondary = Color(0xFF3A2E19),
    secondaryContainer = Color(0xFF52442D),
    onSecondaryContainer = Color(0xFFF5E0C0),
    tertiary = Color(0xFFBAD091),
    onTertiary = Color(0xFF273708),
    tertiaryContainer = Color(0xFF3D4E1D),
    onTertiaryContainer = Color(0xFFD6E9AB),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF282828),
    onBackground = Color(0xFFEBDBB2),
    surface = Color(0xFF282828),
    onSurface = Color(0xFFEBDBB2),
    surfaceVariant = Color(0xFF3C3836),
    onSurfaceVariant = Color(0xFFD8C2BA),
    outline = Color(0xFFA08C84),
    outlineVariant = Color(0xFF53433D),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFFEBDBB2),
    inverseOnSurface = Color(0xFF282828),
    inversePrimary = Color(0xFFAF3A03),
    surfaceTint = Color(0xFFFFB59B),
)

// ── Tokyo Night ──
val TokyoNightLight = AppThemeColors(
    primary = Color(0xFF5B4FC4),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFE3DEFF),
    onPrimaryContainer = Color(0xFF150065),
    secondary = Color(0xFF5C5B72),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFE1DFFA),
    onSecondaryContainer = Color(0xFF19192C),
    tertiary = Color(0xFF396770),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFBCECF7),
    onTertiaryContainer = Color(0xFF001F26),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    background = Color(0xFFFEFBFF),
    onBackground = Color(0xFF1B1B21),
    surface = Color(0xFFFEFBFF),
    onSurface = Color(0xFF1B1B21),
    surfaceVariant = Color(0xFFE5E1EC),
    onSurfaceVariant = Color(0xFF48464F),
    outline = Color(0xFF787680),
    outlineVariant = Color(0xFFC8C5D0),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFF303036),
    inverseOnSurface = Color(0xFFF3EFF4),
    inversePrimary = Color(0xFFC7BFFF),
    surfaceTint = Color(0xFF5B4FC4),
)

val TokyoNightDark = AppThemeColors(
    primary = Color(0xFFC7BFFF),
    onPrimary = Color(0xFF2B1B93),
    primaryContainer = Color(0xFF4337AB),
    onPrimaryContainer = Color(0xFFE3DEFF),
    secondary = Color(0xFFC5C3DD),
    onSecondary = Color(0xFF2E2D42),
    secondaryContainer = Color(0xFF44445A),
    onSecondaryContainer = Color(0xFFE1DFFA),
    tertiary = Color(0xFFA0D1DB),
    onTertiary = Color(0xFF003740),
    tertiaryContainer = Color(0xFF1E4F57),
    onTertiaryContainer = Color(0xFFBCECF7),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF1A1B26),
    onBackground = Color(0xFFE4E4E7),
    surface = Color(0xFF1A1B26),
    onSurface = Color(0xFFE4E4E7),
    surfaceVariant = Color(0xFF2A2B3D),
    onSurfaceVariant = Color(0xFFC8C5D0),
    outline = Color(0xFF928F99),
    outlineVariant = Color(0xFF48464F),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFFE4E4E7),
    inverseOnSurface = Color(0xFF303036),
    inversePrimary = Color(0xFF5B4FC4),
    surfaceTint = Color(0xFFC7BFFF),
)

// ── Nord ──
val NordLight = AppThemeColors(
    primary = Color(0xFF4C566A),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFD0E4F5),
    onPrimaryContainer = Color(0xFF071E2E),
    secondary = Color(0xFF5E81AC),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFE0EAFF),
    onSecondaryContainer = Color(0xFF182A3E),
    tertiary = Color(0xFF88C0D0),
    onTertiary = Color(0xFF003540),
    tertiaryContainer = Color(0xFFC5E7F0),
    onTertiaryContainer = Color(0xFF001F28),
    error = Color(0xFFBF616A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410E0B),
    background = Color(0xFFECEFF4),
    onBackground = Color(0xFF2E3440),
    surface = Color(0xFFECEFF4),
    onSurface = Color(0xFF2E3440),
    surfaceVariant = Color(0xFFD8DEE9),
    onSurfaceVariant = Color(0xFF4C566A),
    outline = Color(0xFF8190A5),
    outlineVariant = Color(0xFFC8D0DB),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFF3B4252),
    inverseOnSurface = Color(0xFFECEFF4),
    inversePrimary = Color(0xFFB8CCE0),
    surfaceTint = Color(0xFF4C566A),
)

val NordDark = AppThemeColors(
    primary = Color(0xFFB8CCE0),
    onPrimary = Color(0xFF1F3547),
    primaryContainer = Color(0xFF354B5E),
    onPrimaryContainer = Color(0xFFD0E4F5),
    secondary = Color(0xFF8CAED4),
    onSecondary = Color(0xFF002B40),
    secondaryContainer = Color(0xFF3F5A74),
    onSecondaryContainer = Color(0xFFE0EAFF),
    tertiary = Color(0xFFA2D4E0),
    onTertiary = Color(0xFF003645),
    tertiaryContainer = Color(0xFF234D5C),
    onTertiaryContainer = Color(0xFFC5E7F0),
    error = Color(0xFFCF6F78),
    onError = Color(0xFF3F1218),
    errorContainer = Color(0xFF5E292F),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF2E3440),
    onBackground = Color(0xFFD8DEE9),
    surface = Color(0xFF2E3440),
    onSurface = Color(0xFFD8DEE9),
    surfaceVariant = Color(0xFF3B4252),
    onSurfaceVariant = Color(0xFFC8D0DB),
    outline = Color(0xFF8F9CAA),
    outlineVariant = Color(0xFF4C566A),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFFD8DEE9),
    inverseOnSurface = Color(0xFF3B4252),
    inversePrimary = Color(0xFF4C566A),
    surfaceTint = Color(0xFFB8CCE0),
)

// ── Dracula ──
val DraculaLight = AppThemeColors(
    primary = Color(0xFFBD5000),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFDCC8),
    onPrimaryContainer = Color(0xFF3E1500),
    secondary = Color(0xFF8B5CF6),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFEBDEFF),
    onSecondaryContainer = Color(0xFF2D0B6B),
    tertiary = Color(0xFF00A86B),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFF8EFFC3),
    onTertiaryContainer = Color(0xFF00331E),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    background = Color(0xFFF8F9FA),
    onBackground = Color(0xFF1A1A1A),
    surface = Color(0xFFF8F9FA),
    onSurface = Color(0xFF1A1A1A),
    surfaceVariant = Color(0xFFE2E2E6),
    onSurfaceVariant = Color(0xFF4A4A4E),
    outline = Color(0xFF7A7A7E),
    outlineVariant = Color(0xFFCBCBCF),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFF2F2F33),
    inverseOnSurface = Color(0xFFF8F9FA),
    inversePrimary = Color(0xFFFFB897),
    surfaceTint = Color(0xFFBD5000),
)

val DraculaDark = AppThemeColors(
    primary = Color(0xFFFFB897),
    onPrimary = Color(0xFF5E2500),
    primaryContainer = Color(0xFF8A3A00),
    onPrimaryContainer = Color(0xFFFFDCC8),
    secondary = Color(0xFFBD93F9),
    onSecondary = Color(0xFF2D0B6B),
    secondaryContainer = Color(0xFF4E2D7C),
    onSecondaryContainer = Color(0xFFEBDEFF),
    tertiary = Color(0xFF50FA7B),
    onTertiary = Color(0xFF00391E),
    tertiaryContainer = Color(0xFF00522E),
    onTertiaryContainer = Color(0xFF8EFFC3),
    error = Color(0xFFFF6E6E),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF282A36),
    onBackground = Color(0xFFF8F8F2),
    surface = Color(0xFF282A36),
    onSurface = Color(0xFFF8F8F2),
    surfaceVariant = Color(0xFF343746),
    onSurfaceVariant = Color(0xFFCBCBCF),
    outline = Color(0xFF959599),
    outlineVariant = Color(0xFF4A4A4E),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFFF8F8F2),
    inverseOnSurface = Color(0xFF282A36),
    inversePrimary = Color(0xFFBD5000),
    surfaceTint = Color(0xFFFFB897),
)

// ── Theme Map ──
sealed class AppTheme(val id: String, val displayName: String) {
    object Default : AppTheme("default", "Default")
    object Dynamic : AppTheme("dynamic", "Dynamic")
    object Catppuccin : AppTheme("catppuccin", "Catppuccin")
    object Gruvbox : AppTheme("gruvbox", "Gruvbox")
    object TokyoNight : AppTheme("tokyo_night", "Tokyo Night")
    object Nord : AppTheme("nord", "Nord")
    object Dracula : AppTheme("dracula", "Dracula")

    companion object {
        fun fromId(id: String): AppTheme = when (id) {
            "default" -> Default
            "dynamic" -> Dynamic
            "catppuccin" -> Catppuccin
            "gruvbox" -> Gruvbox
            "tokyo_night" -> TokyoNight
            "nord" -> Nord
            "dracula" -> Dracula
            else -> Dynamic
        }

        val all = listOf(Default, Dynamic, Catppuccin, Gruvbox, TokyoNight, Nord, Dracula)
    }
}

fun AppTheme.getColors(isDark: Boolean, isAmoled: Boolean = false): AppThemeColors = when (this) {
    is AppTheme.Default -> if (isDark) DefaultDark else DefaultLight
    is AppTheme.Catppuccin -> if (isDark) CatppuccinDark else CatppuccinLight
    is AppTheme.Gruvbox -> if (isDark) GruvboxDark else GruvboxLight
    is AppTheme.TokyoNight -> if (isDark) TokyoNightDark else TokyoNightLight
    is AppTheme.Nord -> if (isDark) NordDark else NordLight
    is AppTheme.Dracula -> if (isDark) DraculaDark else DraculaLight
    is AppTheme.Dynamic -> throw IllegalStateException("Dynamic theme handled separately")
}
